ifdef CONFIG_MACH_APQ8064_OMEGAR_KR
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4) += board-omega-input.o
obj-$(CONFIG_RMI4_I2C) += board-omega-input.o
else
ifdef CONFIG_MACH_APQ8064_OMEGA_KR
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4) += board-omega-input.o
obj-$(CONFIG_RMI4_I2C) += board-omega-input.o
else
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4) += board-g-input.o
obj-$(CONFIG_RMI4_I2C) += board-g-input.o
endif
endif
