obj-$(CONFIG_MACH_APQ8064_GVAR_CMCC) += board-gvar.o \
	board-gvar-camera.o \
	board-gvar-display.o \
	board-gvar-gpiomux.o \
	board-gvar-gpu.o \
	board-gvar-pmic.o \
	board-gvar-input.o \
	board-gvar-regulator.o \
	board-gvar-misc.o \
	board-gvar-sound.o \
	board-gvar-storage.o \
	board-gvar-nfc.o \
	board-gvar-rfkill.o

