obj-$(CONFIG_MACH_APQ8064_AWIFI) += board-awifi.o
obj-$(CONFIG_MACH_APQ8064_ALTEV) += board-altev.o

obj-y += \
	board-awifi-camera.o \
	board-awifi-display.o \
	board-awifi-gpiomux.o \
	board-awifi-gpu.o \
	board-awifi-pmic.o \
	board-awifi-regulator.o \
	board-awifi-misc.o \
	board-awifi-sound.o \
	board-awifi-storage.o \
	board-awifi-rfkill.o
	
	
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT1188S) += board-awifi-input.o
obj-$(CONFIG_LGE_NFC) += board-awifi-nfc.o
