obj-$(CONFIG_MACH_APQ8064_AWIFI) += board-awifi.o \
	board-awifi-camera.o \
	board-awifi-display.o \
	board-awifi-gpiomux.o \
	board-awifi-gpu.o \
	board-awifi-pmic.o \
	board-awifi-regulator.o \
	board-awifi-misc.o \
	board-awifi-sound.o \
	board-awifi-storage.o \
	board-awifi-nfc.o \
	board-awifi-rfkill.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT1188S) += board-awifi-input.o