obj-$(CONFIG_MACH_APQ8064_OMEGA) += board-omega.o \
	board-omega-camera.o \
	board-omega-display.o \
	board-omega-gpiomux.o \
	board-omega-gpu.o \
	board-omega-pmic.o \
	board-omega-regulator.o \
	board-omega-misc.o \
	board-omega-sound.o \
	board-omega-storage.o \
	board-omega-nfc.o \
	board-omega-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKU) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKSK) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKKT) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKATT) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

obj-$(CONFIG_MACH_APQ8064_GKGLOBAL) += board-gk.o \
	board-gk-camera.o \
	board-gk-display.o \
	board-gk-gpiomux.o \
	board-gk-gpu.o \
	board-gk-pmic.o \
	board-gk-regulator.o \
	board-gk-misc.o \
	board-gk-sound.o \
	board-gk-storage.o \
	board-gk-nfc.o \
	board-gk-rfkill.o

